name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
category-template: '### $TITLE'
categories:
  - title: 'Features'
    labels:
      - 'Feature Request'
      - 'Feature: Provider'
      - 'Feature: Type'
      - 'Feature: Value'
      - 'Feature: Operation'
  - title: 'Module: Complex Numbers'
    labels:
      - 'Module: Complex Numbers'
  - title: 'Module: Coordinates'
    labels:
      - 'Module: Coordinate Systems'
  - title: 'Module: Linear Algebra'
    labels:
      - 'Module: Matrices and Vectors'
  - title: 'Module: Statistics'
    labels:
      - 'Module: Stats'
  - title: 'Module: Expressions'
    labels:
      - 'Module: Algebra Expressions'
  - title: 'Bug Fixes'
    labels:
      - 'Bug'
  - title: 'Maintenance'
    labels:
      - 'Code Quality'
      - 'Performance'
      - 'UX Improvement'
change-template: '- $TITLE (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-labels:
  - 'PR: Skip Changelog'
version-resolver:
  major:
    labels:
      - 'PR: Major'
  minor:
    labels:
      - 'PR: Minor'
  patch:
    labels:
      - 'PR: Patch'
  default: patch
autolabeler:
  - label: 'PR: Major'
    title:
      - '/changed/i'
  - label: 'PR: Minor'
    title:
      - '/added/i'
      - '/updated/i'
  - label: 'PR: Patch'
    branch:
      - '/bug-/i'
      - '/b-/i'
  - label: 'Bug'
    title:
      - '/fix/i'
    branch:
      - '/bug-/i'
      - '/b-/i'
template: |
  ## Included In This Release

  $CHANGES