version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 8
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "phpmdRuleset.xml"
exclude_patterns:
  - ".circleci/"
  - ".github/"
  - "backup/"
  - "build/"
  - "docs/"
  - "site/"
  - "tests/"
  - "tests-bench/"
  - "vendor/"
  - "*.json"
  - "*.yml"
  - "*.md"
  - "*.xml"
  - "**/Enums/*.php"
  - "**/*Interface.php"
  - ".*.yml"
  - ".gitignore"
  - "LICENSE"
  - "COPYRIGHT"