version: "2"
checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 350
  method-complexity:
    enabled: true
    config:
      threshold: 15
  method-count:
    enabled: true
    config:
      threshold: 30
  method-lines:
    enabled: true
    config:
      threshold: 30
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 15
  identical-code:
    enabled: true
    config:
      threshold: 15
exclude_patterns:
  - ".circleci/"
  - ".github/"
  - "backup/"
  - "build/"
  - "docs/"
  - "site/"
  - "tests/"
  - "tests-bench/"
  - "vendor/"
  - "*.json"
  - "*.yml"
  - "*.md"
  - "*.xml"