build:
    nodes:
        analysis:
            environment:
                variables:
                    COMPOSER_ROOT_VERSION: 2.0
                php:
                    version: 8.1
                    ini:
                        xdebug.mode: coverage
            tests:
                override:
                    - php-scrutinizer-run
        standalone-tests:
            environment:
                variables:
                    COMPOSER_ROOT_VERSION: 2.0
                php:
                    version: 8.1
                    ini:
                        xdebug.mode: coverage
            tests:
                before:
                    - mkdir build
                    - mkdir build/logs
                override:
                    - command: php vendor/bin/phpunit --group=DecimalLegacy
                      on_node: 1
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
                    - command: php vendor/bin/phpunit --group=ArithmeticAuto
                      on_node: 2
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
                    - command: php vendor/bin/phpunit --group=ArithmeticNative
                      on_node: 3
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
                    - command: php vendor/bin/phpunit --group=ArithmeticPrecision
                      on_node: 4
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
                    - command: php vendor/bin/phpunit --group=Types
                      on_node: 5
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
                    - command: php vendor/bin/phpunit --group=Providers
                      on_node: 6
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
                    - command: php vendor/bin/phpunit --group=BasicTrigonometry
                      on_node: 7
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
        standalone-tests-with-decimal:
            environment:
                apt_packages:
                    - php-decimal
                variables:
                    COMPOSER_ROOT_VERSION: 2.0
                php:
                    version: 8.1
                    ini:
                        xdebug.mode: coverage
            tests:
                before:
                    - mkdir build
                    - mkdir build/logs
                override:
                    - command: php vendor/bin/phpunit --group=DecimalLegacy
                      on_node: 1
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
                    - command: php vendor/bin/phpunit --group=ArithmeticAuto
                      on_node: 2
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
                    - command: php vendor/bin/phpunit --group=ArithmeticNative
                      on_node: 3
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
                    - command: php vendor/bin/phpunit --group=ArithmeticPrecision
                      on_node: 4
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
                    - command: php vendor/bin/phpunit --group=Types
                      on_node: 5
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
                    - command: php vendor/bin/phpunit --group=Providers
                      on_node: 6
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
                    - command: php vendor/bin/phpunit --group=BasicTrigonometry
                      on_node: 7
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
        with-modules-tests:
            environment:
                apt_packages:
                    - php-decimal
                variables:
                    COMPOSER_ROOT_VERSION: 2.0
                php:
                    version: 8.1
                    ini:
                        xdebug.mode: coverage
            requires:
                - node: standalone-tests
            tests:
                before:
                    - mkdir build
                    - mkdir build/logs
                    - composer require -w "samsara/fermat-coordinate-systems:dev-master@dev"
                    - composer require -w "samsara/fermat-complex-numbers:dev-master@dev"
                    - composer require -w "samsara/fermat-matrices-and-vectors:dev-master@dev"
                    - composer require -w "samsara/fermat-stats:dev-master@dev"
                    - composer require -w "samsara/fermat-algebra-expressions:dev-master@dev"
                override:
                    - command: php vendor/bin/phpunit -c phpunit-modules.xml
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
build_failure_conditions:
    - 'project.metric_change("scrutinizer.test_coverage", < -0.05)'
    - 'project.metric("scrutinizer.test_coverage", < 0.70)'
    - 'project.metric("scrutinizer.quality", < 8)'