build:
    environment:
        variables:
            COMPOSER_ROOT_VERSION: 2.0
        php:
            version: 8.1
            ini:
                xdebug.mode: coverage
    nodes:
        standalone-tests:
            tests:
                before:
                    - mkdir build
                    - mkdir build/logs
                override:
                    - command: php vendor/bin/phpunit
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
        with-modules-tests:
            requires:
                - node: standalone-tests
            tests:
                before:
                    - mkdir build
                    - mkdir build/logs
                    - composer require -w "samsara/fermat-coordinate-systems:dev-master@dev"
                    - composer require -w "samsara/fermat-complex-numbers:dev-master@dev"
                    - composer require -w "samsara/fermat-matrices-and-vectors:dev-master@dev"
                    - composer require -w "samsara/fermat-stats:dev-master@dev"
                    - composer require -w "samsara/fermat-algebra-expressions:dev-master@dev"
                override:
                    - command: php vendor/bin/phpunit -c phpunit-modules.xml
                      coverage:
                          file: build/logs/coverage.clover
                          format: clover
build_failure_conditions:
    - 'project.metric_change("scrutinizer.test_coverage", < -0.05)'
    - 'project.metric("scrutinizer.test_coverage", < 0.70)'
    - 'project.metric("scrutinizer.quality", < 8)'