language: php
php:
  - 8.0

install:
  - composer update

before_script:
  - mkdir build
  - mkdir build/logs

script:
  - php vendor/bin/phpunit

after_success:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/coverage.clover