site_name: Fermat - PHP Math Library
extra_css:
  - css/custom.css
repo_url: https://github.com/JordanRL/Fermat/
nav:
  - 'Introduction': 'index.md'
  - 'Getting Started':
      - 'Concepts': 'getting-started/concepts.md'
      - 'Installation & Usage': 'getting-started/installation-and-usage.md'
      - 'Using The Factories': 'getting-started/using-factories.md'
      - 'Direct Instantiation': 'getting-started/direct-instantiation.md'
      - 'Comparing Values': 'getting-started/comparing.md'
      - 'Calculation Modes': 'getting-started/calculation-modes.md'
      - 'Mutable vs. Immutable': 'getting-started/mutability.md'
      - 'Handling Exceptions': 'getting-started/exceptions.md'
  - 'Types & Values':
      - 'Decimals': 'types-and-values/decimals.md'
      - 'Fractions': 'types-and-values/fractions.md'
      - 'Complex Numbers': 'types-and-values/complex.md'
      - 'Coordinates': 'types-and-values/coordinates.md'
      - 'Matrices': 'types-and-values/matrices.md'
      - 'Collections': 'types-and-values/collections.md'
      - 'Expressions': 'types-and-values/expressions.md'
  - 'Arithmetic': 'arithmetic/index.md'
  - 'Trigonometry':
      - 'Basic Trig Functions': 'trigonometry/basic.md'
      - 'Inverse Trig Functions': 'trigonometry/inverse.md'
      - 'Hyperbolic Trig Functions': 'trigonometry/hyperbolic.md'
  - 'Statistics':
      - 'Using Distributions': 'statistics/distributions.md'
      - 'Using Static Methods': 'statistics/static-methods.md'
  - 'Extending': 'test.md'
  - 'REFERENCE':
      - 'Interfaces':
          - Numbers: 'reference/interfaces/numbers.md'
          - Groups: 'reference/interfaces/groups.md'
          - Coordinates: 'reference/interfaces/coordinates.md'
          - Evaluateables: 'reference/interfaces/evaluateables.md'
          - Characteristics: 'reference/interfaces/characteristics.md'
      - 'Providers': 'test.md'
      - 'Distributions': 'test.md'
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - php
  titles_only: true
markdown_extensions:
  - codehilite
  - toc:
      toc_depth: 2
  - admonition