site_name: Fermat - PHP Math Library
nav:
  - 'Introduction': 'index.md'
  - 'Getting Started': 'getting-started/index.md'
  - 'Helper Methods': 'helpers/index.md'
  - 'Arithmetic': 'arithmetic/index.md'
  - 'Trigonometry': 'trigonometry/index.md'
theme: readthedocs