site_name: 'Fermat - PHP Math Library'
extra_css:
    - css/md-theme.css
    - css/custom.css
repo_url: 'https://github.com/JordanRL/Fermat/'
site_url: 'https://jordanrl.github.io/Fermat/'
copyright: 'Copyright &copy; 2015-2022 Jordan LeDoux'
nav:
    -
        Introduction:
            -
                'About Fermat': index.md
            -
                'Fermat vs. Alternatives': fermat-vs-alternatives.md
    -
        'Getting Started':
            -
                Concepts: getting-started/concepts.md
            -
                'Installation & Usage': getting-started/installation-and-usage.md
            -
                'Mutable vs. Immutable': getting-started/mutability.md
            -
                'Using The Factories': getting-started/using-factories.md
            -
                'Comparing Values': getting-started/comparing.md
            -
                'Handling Exceptions': getting-started/exceptions.md
            -
                Modules: getting-started/modules.md
            -
                'Use Case Guides':
                    -
                        'Scalar Replacements': getting-started/how-to-replace-scalars.md
    -
        Performance:
            -
                Overview: performance/overview.md
            -
                'Performance Stats':
                    -
                        Arithmetic: performance/arithmetic.md
                    -
                        Logarithms: performance/logarithms.md
                    -
                        Trigonometry: performance/trigonometry.md
    -
        Configuration:
            -
                'Calculation Modes': configuration/calculation-modes.md
            -
                'Random Modes': configuration/random-modes.md
            -
                'Rounding Modes': configuration/rounding-modes.md
            -
                'Base Conversion': configuration/base-conversion.md
    -
        Modules:
            -
                'Stable Modules':
                    -
                        'Coordinate Systems': modules/coordinate-systems/about.md
                    -
                        Stats: modules/stats/about.md
            -
                'Unstable Modules':
                    -
                        'Algebra Expressions': modules/algebra-expressions/about.md
                    -
                        'Complex Numbers': modules/complex-numbers/about.md
                    -
                        'Linear Algebra': modules/linear-algebra/about.md
    -
        'Source Reference':
            -
                'Fermat Core':
                    -
                        Numbers: 'roster/latest/Fermat Core/Numbers.md'
                    -
                        Collections: 'roster/latest/Fermat Core/Collections.md'
                    -
                        Values:
                            -
                                MutableDecimal: 'roster/latest/Fermat Core/Values/MutableDecimal.md'
                            -
                                ImmutableDecimal: 'roster/latest/Fermat Core/Values/ImmutableDecimal.md'
                            -
                                ImmutableFraction: 'roster/latest/Fermat Core/Values/ImmutableFraction.md'
                            -
                                MutableFraction: 'roster/latest/Fermat Core/Values/MutableFraction.md'
                    -
                        Types:
                            -
                                Fraction: 'roster/latest/Fermat Core/Types/Fraction.md'
                            -
                                NumberCollection: 'roster/latest/Fermat Core/Types/NumberCollection.md'
                            -
                                Decimal: 'roster/latest/Fermat Core/Types/Decimal.md'
                            -
                                Tuple: 'roster/latest/Fermat Core/Types/Tuple.md'
                            -
                                Base:
                                    -
                                        Number: 'roster/latest/Fermat Core/Types/Base/Number.md'
                                    -
                                        Interfaces:
                                            -
                                                Numbers:
                                                    -
                                                        NumberInterface: 'roster/latest/Fermat Core/Types/Base/Interfaces/Numbers/NumberInterface.md'
                                                    -
                                                        DecimalInterface: 'roster/latest/Fermat Core/Types/Base/Interfaces/Numbers/DecimalInterface.md'
                                                    -
                                                        FractionInterface: 'roster/latest/Fermat Core/Types/Base/Interfaces/Numbers/FractionInterface.md'
                                                    -
                                                        SimpleNumberInterface: 'roster/latest/Fermat Core/Types/Base/Interfaces/Numbers/SimpleNumberInterface.md'
                                            -
                                                Callables:
                                                    -
                                                        ContinuedFractionTermInterface: 'roster/latest/Fermat Core/Types/Base/Interfaces/Callables/ContinuedFractionTermInterface.md'
                                            -
                                                Groups:
                                                    -
                                                        NumberCollectionInterface: 'roster/latest/Fermat Core/Types/Base/Interfaces/Groups/NumberCollectionInterface.md'
                            -
                                Traits:
                                    -
                                        ComparisonTrait: 'roster/latest/Fermat Core/Types/Traits/ComparisonTrait.md'
                                    -
                                        ArithmeticSimpleTrait: 'roster/latest/Fermat Core/Types/Traits/ArithmeticSimpleTrait.md'
                                    -
                                        InverseTrigonometrySimpleTrait: 'roster/latest/Fermat Core/Types/Traits/InverseTrigonometrySimpleTrait.md'
                                    -
                                        IntegerMathTrait: 'roster/latest/Fermat Core/Types/Traits/IntegerMathTrait.md'
                                    -
                                        TrigonometrySimpleTrait: 'roster/latest/Fermat Core/Types/Traits/TrigonometrySimpleTrait.md'
                                    -
                                        LogSimpleTrait: 'roster/latest/Fermat Core/Types/Traits/LogSimpleTrait.md'
                                    -
                                        Trigonometry:
                                            -
                                                TrigonometrySelectionTrait: 'roster/latest/Fermat Core/Types/Traits/Trigonometry/TrigonometrySelectionTrait.md'
                                            -
                                                InverseTrigonometryNativeTrait: 'roster/latest/Fermat Core/Types/Traits/Trigonometry/InverseTrigonometryNativeTrait.md'
                                            -
                                                InverseTrigonometrySelectionTrait: 'roster/latest/Fermat Core/Types/Traits/Trigonometry/InverseTrigonometrySelectionTrait.md'
                                            -
                                                TrigonometryScaleTrait: 'roster/latest/Fermat Core/Types/Traits/Trigonometry/TrigonometryScaleTrait.md'
                                            -
                                                InverseTrigonometryScaleTrait: 'roster/latest/Fermat Core/Types/Traits/Trigonometry/InverseTrigonometryScaleTrait.md'
                                            -
                                                TrigonometryNativeTrait: 'roster/latest/Fermat Core/Types/Traits/Trigonometry/TrigonometryNativeTrait.md'
                                    -
                                        Arithmetic:
                                            -
                                                ArithmeticGMPTrait: 'roster/latest/Fermat Core/Types/Traits/Arithmetic/ArithmeticGMPTrait.md'
                                            -
                                                ArithmeticSelectionTrait: 'roster/latest/Fermat Core/Types/Traits/Arithmetic/ArithmeticSelectionTrait.md'
                                            -
                                                ArithmeticScaleTrait: 'roster/latest/Fermat Core/Types/Traits/Arithmetic/ArithmeticScaleTrait.md'
                                            -
                                                ArithmeticNativeTrait: 'roster/latest/Fermat Core/Types/Traits/Arithmetic/ArithmeticNativeTrait.md'
                                    -
                                        Decimal:
                                            -
                                                LogScaleTrait: 'roster/latest/Fermat Core/Types/Traits/Decimal/LogScaleTrait.md'
                                            -
                                                ScaleTrait: 'roster/latest/Fermat Core/Types/Traits/Decimal/ScaleTrait.md'
                                            -
                                                LogNativeTrait: 'roster/latest/Fermat Core/Types/Traits/Decimal/LogNativeTrait.md'
                                            -
                                                LogSelectionTrait: 'roster/latest/Fermat Core/Types/Traits/Decimal/LogSelectionTrait.md'
                    -
                        Provider:
                            -
                                TrigonometryProvider: 'roster/latest/Fermat Core/Provider/TrigonometryProvider.md'
                            -
                                SeriesProvider: 'roster/latest/Fermat Core/Provider/SeriesProvider.md'
                            -
                                RoundingProvider: 'roster/latest/Fermat Core/Provider/RoundingProvider.md'
                            -
                                ConstantProvider: 'roster/latest/Fermat Core/Provider/ConstantProvider.md'
                            -
                                SequenceProvider: 'roster/latest/Fermat Core/Provider/SequenceProvider.md'
                            -
                                BaseConversionProvider: 'roster/latest/Fermat Core/Provider/BaseConversionProvider.md'
                            -
                                ArithmeticProvider: 'roster/latest/Fermat Core/Provider/ArithmeticProvider.md'
                            -
                                CalculationModeProvider: 'roster/latest/Fermat Core/Provider/CalculationModeProvider.md'
                            -
                                RandomProvider: 'roster/latest/Fermat Core/Provider/RandomProvider.md'
            -
                'Fermat Stats':
                    -
                        Values:
                            -
                                Distribution:
                                    -
                                        Normal: 'roster/latest/Fermat Stats/Values/Distribution/Normal.md'
                                    -
                                        Exponential: 'roster/latest/Fermat Stats/Values/Distribution/Exponential.md'
                                    -
                                        Poisson: 'roster/latest/Fermat Stats/Values/Distribution/Poisson.md'
                    -
                        Types:
                            -
                                Distribution: 'roster/latest/Fermat Stats/Types/Distribution.md'
                    -
                        Provider:
                            -
                                StatsProvider: 'roster/latest/Fermat Stats/Provider/StatsProvider.md'
            -
                'Fermat Coordinate Systems':
                    -
                        Values:
                            -
                                Geometry:
                                    -
                                        CoordinateSystems:
                                            -
                                                PolarCoordinate: 'roster/latest/Fermat Coordinate Systems/Values/Geometry/CoordinateSystems/PolarCoordinate.md'
                                            -
                                                CylindricalCoordinate: 'roster/latest/Fermat Coordinate Systems/Values/Geometry/CoordinateSystems/CylindricalCoordinate.md'
                                            -
                                                SphericalCoordinate: 'roster/latest/Fermat Coordinate Systems/Values/Geometry/CoordinateSystems/SphericalCoordinate.md'
                                            -
                                                CartesianCoordinate: 'roster/latest/Fermat Coordinate Systems/Values/Geometry/CoordinateSystems/CartesianCoordinate.md'
                    -
                        Types:
                            -
                                Coordinate: 'roster/latest/Fermat Coordinate Systems/Types/Coordinate.md'
                            -
                                Base:
                                    -
                                        Interfaces:
                                            -
                                                Coordinates:
                                                    -
                                                        ThreeDCoordinateInterface: 'roster/latest/Fermat Coordinate Systems/Types/Base/Interfaces/Coordinates/ThreeDCoordinateInterface.md'
                                                    -
                                                        TwoDCoordinateInterface: 'roster/latest/Fermat Coordinate Systems/Types/Base/Interfaces/Coordinates/TwoDCoordinateInterface.md'
                                                    -
                                                        CoordinateInterface: 'roster/latest/Fermat Coordinate Systems/Types/Base/Interfaces/Coordinates/CoordinateInterface.md'
theme:
    palette:
        -
            media: '(prefers-color-scheme: light)'
            scheme: default
            toggle:
                icon: material/toggle-switch-off-outline
                name: 'Switch to dark mode'
        -
            media: '(prefers-color-scheme: dark)'
            scheme: slate
            toggle:
                icon: material/toggle-switch
                name: 'Switch to light mode'
    name: material
    features:
        - navigation.sections
        - navigation.top
        - navigation.tabs
    highlightjs: true
    hljs_languages:
        - php
markdown_extensions:
    -
        toc:
            toc_depth: 5
    - admonition
    -
        markdown_katex:
            no_inline_svg: true
            insert_fonts_css: true
    - pymdownx.tabbed
    - pymdownx.superfences
    -
        pymdownx.highlight:
            linenums: true
            linenums_style: inline
    -
        pymdownx.snippets:
            base_path: ./docs/snippets
            check_paths: true
    - pymdownx.extra
