site_name: Fermat - PHP Math Library
extra_css: [custom.css]
nav:
  - 'Introduction': 'index.md'
  - 'Getting Started': 'getting-started/index.md'
  - 'Helper Methods': 'helpers/index.md'
  - 'Arithmetic': 'arithmetic/index.md'
  - 'Trigonometry': 'trigonometry/index.md'
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - php
  titles_only: true
markdown_extensions:
  - codehilite
  - toc:
      toc_depth: 2
  - admonition