site_name: Fermat - PHP Math Library
extra_css:
  - css/custom.css
nav:
  - 'Introduction': 'index.md'
  - 'Getting Started': 'getting-started/index.md'
  - 'Interfaces':
      - Numbers: 'interfaces/numbers.md'
      - Groups: 'interfaces/groups.md'
      - Coordinates: 'interfaces/coordinates.md'
      - Evaluateables: 'interfaces/evaluateables.md'
      - Characteristics: 'interfaces/characteristics.md'
  - 'Arithmetic': 'arithmetic/index.md'
  - 'Trigonometry': 'trigonometry/index.md'
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - php
  titles_only: true
markdown_extensions:
  - codehilite
  - toc:
      toc_depth: 2
  - admonition