version: 2.1

jobs:
  coverage-bcmath:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - run:
          name: "Updating Composer"
          command: "composer update"
      - run:
          name: "Running PHPUnit With BCMath"
          command:
            - "vendor/bin/phpunit"

workflows:
  unit-test-workflow:
    jobs:
      - coverage-bcmath
