version: 2.1

jobs:
  coverage-bcmath:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - composer update
      - vendor/bin/phpunit

workflows:
  unit-test-workflow:
    jobs:
      - coverage-bcmath
