name: Circle CI

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'src/**'
      - 'tests/**'
    branches:
      - master

jobs:
  trigger_circle_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI Pipeline
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.5
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}